congregation/urls.py
from django.conf.urls.defaults import *
from django.views.generic import list_detail
from congregation.models import *

urlpatterns = patterns('congregation.views',
    url (r'^$',
        view='congregation_home',
        name='congregation_home'
    ),

    url(r'^households/$',
        view='household_list', 
        name='households_list'),

    url(r'^households/(?P<slug>[-\w]+)/$',
        view='household_detail',
        name='household_detail'
    ),

    url(r'^people/$',
        view='person_list',
        name='person_list'
    ),
    url(r'^people/(?P<slug>[-\w]+)/$',
        view='person_detail',
        name='person_detail'
    ),

    url(r'^profile-manager/$',
        view='profile_manager',
        name='profile_manager'
    ),

    url(r'^household-manager/$',
        view='household_manager',
        name='household_manager'
    ),

    url(r'^groups/$',
        view='group_list',
        name='group_list'
    ),
    url(r'^groups/(?P<slug>[-\w]+)/$',
        view='group_detail',
        name='group_detail'
    ),

    url(r'^mailboxes/$',
        view='mailbox_list',
        name='mailbox_list'
    ),
    url(r'^mailboxes/(?P<slug>[-\w]+)/$',
        view='mailbox_detail',
        name='mailbox_detail'
    ),
    url(r'^talents/$',
        view='talents_list',
        name='talents_list'
    ),
    url(r'^talents/(?P<slug>[-\w]+)/$',
        view='talents_detail',
        name='talents_detail'
    ),
    url(r'^search/', view='search', name='congregation_search'),
)

urls.py
from django.conf.urls.defaults import *
from bslcks.feeds import LatestNewsFeed

#Admin
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),

    (r'^photos/', include('photologue.urls')),
    (r'^congregation/', include('congregation.urls')),
    (r'^news/',      include('basic.blog.urls')),
    (r'^bookmarks/', include('basic.bookmarks.urls')),
    (r'^comments/', include('basic.comments.urls')),
    #(r'^mission/', include('basic.mission.urls')),
    (r'^places/', include('basic.places.urls')),
    (r'^dailybread/', include('dailybread.urls')),
    (r'^surveys/', include('survey.urls')),
    (r'^rss/', LatestNewsFeed()),
)


urlpatterns += patterns('django.contrib.auth.views',
    url(r'^accounts/login/$', 'login', name='accounts_login'),
    url(r'^accounts/logout/$', 'logout', {'next_page': '/',}),

    url(r'^accounts/password-change/$', 'password_change', name='password_change'),
    url(r'^accounts/password-change/success/$', 'password_change_done'),

    url(r'^accounts/password-reset/$', 'password_reset'),
    url(r'^accounts/password-reset/done/$', 'password_reset_done'),

    url(r'^accounts/password-reset-confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 'password_reset_confirm'),
    url(r'^accounts/reset/done/$', 'password_reset_complete'),


)

urlpatterns += patterns('bslcks.views',
    url(r'^$',
        view='Homepage',
        name='home'),

    url(r'^map/',
        view='Map',
        name='map'),

    url(r'^staff/',
        view='Staff',
        name='staff'),

    url(r'^accounts/$',
        view='redirect_home')
)

congregation/models.py
from django.conf import settings
from django.db.models import permalink
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.db.models import Count
from django.contrib.localflavor.us.models import *
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import pre_save
from django.core.signals import request_finished

import re
from datetime import datetime
from dateutil.relativedelta import *

from photologue.models import Photo

class UserLogin(models.Model):
    """Represent users' logins, one per record"""
    user = models.ForeignKey(User)
    timestamp = models.DateTimeField()

    def __unicode__(self):
        try:
            p = self.user.get_profile()
            return u'%s on %s' % (p, self.timestamp)
        except:
            return u'%s on %s' % (self.user, self.timestamp) 

@receiver(pre_save, sender=User, dispatch_uid='LoginCounter')
def user_presave(sender, instance, **kwargs):
    try:
        if instance.last_login:
            old = instance.__class__.objects.get(pk=instance.pk)
            if instance.last_login != old.last_login:
                instance.userlogin_set.create(timestamp=instance.last_login)
    except:
        pass


class Talents(models.Model):
    name = models.CharField('talent name', max_length=100)
    slug = models.SlugField('slug', unique=True)
    category = models.ForeignKey('self', blank=True, null=True, related_name='sub-category')

    class Meta:
        verbose_name = 'talent'
        verbose_name_plural = 'talents'
        ordering = ('name',)

class Role(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField('slug', unique=True)
    

    def __unicode__(self):
        return '%s' % self.name

    class Meta:
        verbose_name = 'role'
        verbose_name_plural = 'roles'
        ordering = ('name',)     


class Household(models.Model):
    name = models.CharField('household name', max_length=100)
    slug = models.SlugField('slug', unique=True)
    address = models.CharField('physical address', max_length=100)
    apartment = models.CharField('apartment/unit number', blank=True, max_length=10)
    zipcode = models.CharField('5 digit zip code', max_length=5)
    state = USStateField('state')
    household_phone = PhoneNumberField('household phone', blank=True)
    unlisted_number = models.BooleanField(default=False)
    bslc_household = models.IntegerField('BSLC DB Household #', blank=True, unique=True)
    picture = models.ForeignKey(Photo, blank=True, null=True)

    class Meta:
        verbose_name = 'household'
        verbose_name_plural = 'households'
        ordering = ['name']

    def __unicode__(self):
        return self.name

    @property
    def last_name(self):
        lname = re.search(r'[^ ]*$',self.name)
        return self.name[lname.start():lname.end()]

    @permalink
    def get_absolute_url(self):
        return ('household_detail', None, {'slug': self.slug}) 

    @property
    def full_address(self):
        addy = ''
        if self.address:
            addy += self.address
            addy += ' '
        if self.apartment:
            addy += self.apartment
            addy += ', '
        else:
            addy += ', '
        if self.zipcode:
            addy += self.zipcode
        return addy

class Prefix(models.Model):
    prefix = models.CharField(max_length=20)
    initials = models.CharField(max_length=5)

    def __unicode__(self):
        return u'%s (%s)' % (self.initials.capitalize(),self.prefix.capitalize())

class Person(models.Model):
    """Person model."""
    GENDER_CHOICES = (
        ('m', 'Male'),
        ('f', 'Female'),
    )

    prefix = models.ForeignKey('prefix', blank=True, null=True)
    first_name = models.CharField('first name', blank=True, max_length=100)
    preferred_first_name = models.CharField(blank=True, max_length=100)
    middle_name = models.CharField('middle name', blank=True, max_length=100)
    last_name = models.CharField('last name', blank=True, max_length=100)
    suffix = models.CharField('suffix', max_length=10, blank=True)

    slug = models.SlugField('slug', unique=True)
    user = models.ForeignKey(User, blank=True, null=True, help_text='If the person is an existing site user')

    gender = models.CharField('gender',choices=GENDER_CHOICES, max_length=1)
    birth_date = models.DateField('birth date', blank=True, null=True)
    baptism_date = models.DateField('baptism date', blank=True, null=True)

    active = models.BooleanField(default=True)
    member = models.BooleanField(default=True)
    role = models.ManyToManyField(Role, blank=True, null=True)
    opt_in_directory = models.BooleanField('opt-in to directory', default=True)
    directory_report_order = models.IntegerField(blank=True, null=True)

    joined = models.DateField('member since', blank=True, null=True)
    left = models.DateField('left on', blank=True, null=True)

    talents = models.ManyToManyField(Talents, blank=True, null=True)

    relations = models.ManyToManyField("self", blank=True, null=True)
    household = models.ForeignKey(Household, blank=True, null=True)

    bio = models.TextField('biography', blank=True)
    picture = models.ForeignKey(Photo, blank=True, null=True)

    email = models.EmailField(blank=True)
    landline = PhoneNumberField('landline phone', blank=True)
    cellphone = PhoneNumberField('cell phone', blank=True)

    deceased = models.DateField(null=True, blank=True)

    bslc_individual = models.CharField('BSLC DB Individual #', blank=True, null=True, max_length=15, unique=True)

    class Meta:
        verbose_name = 'person'
        verbose_name_plural = 'people'
        ordering = ('last_name', 'first_name',)
        unique_together = ('last_name', 'first_name', 'user')

    def __unicode__(self):
        return u'%s' % self.full_name

    def save(self, *args, **kwargs):
        try:
            self.user.email = self.email
            self.user.save()
        except:
            pass
        super(Person, self).save(*args, **kwargs) # Call the "real" save() method.

    @property
    def full_name(self):
        if self.preferred_first_name:
            return u'%s %s' % (self.preferred_first_name, self.last_name)
        else:
            return u'%s %s' % (self.first_name, self.last_name)

    @property
    def age(self):
        if self.birth_date:
            TODAY = datetime.today()
            return relativedelta(TODAY, self.birth_date).years
        else:
            return
    
    @property
    def age_days(self):
        if self.birth_date:
            TODAY = datetime.today().date()
            diff = TODAY - self.birth_date
            return diff.days
        else:
            return

    @permalink
    def get_absolute_url(self):
        return ('person_detail', None, {'slug': self.slug}) 

#def create_user_profile(sender, instance, created, **kwargs):
#    if created:
#        Person.objects.create(user=instance)

#post_save.connect(create_user_profile, sender=User)

class GroupType(models.Model):
    name = models.CharField('group type name', max_length=100)
    slug = models.SlugField('slug', unique=True)

    def __unicode__(self):
        return '%s' % self.name

class Group(models.Model):
    name = models.CharField('group name', max_length=100)
    slug = models.SlugField('slug', unique=True)
    gtype = models.ForeignKey(GroupType, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    avatar = models.ForeignKey(Photo, blank=True, null=True)
    leaders = models.ManyToManyField(Person, related_name='leaders')
    members = models.ManyToManyField(Person, related_name='members', blank = True, null = True)

    talents = models.ManyToManyField(Talents, blank=True)

    active = models.BooleanField(default=True)

    def __unicode__(self):
        return u'%s' % self.name

    @permalink
    def get_absolute_url(self):
        return ('group_detail', None, {'slug': self.slug})


class Mailbox(models.Model):
    number = models.IntegerField(unique=True)
    occupants = models.ManyToManyField(Person)

    class Meta:
        verbose_name = 'mailbox'
        verbose_name_plural = 'mailboxes'
        ordering = ('number',)

    def occupants_list(self):
        names = ''
        occs = self.occupants.order_by('birth_date').values_list('first_name', 'last_name')
        thecount = 1
        themax = len(occs)

        for occupant in occs:
            names += '%s %s' % (occupant[0], occupant[1])
            if thecount < themax:
               names += ', '
               if (themax-1) == thecount:
                   names += ' and '
            thecount +=1
        return names

    @property
    def num_occupants(self):
        return self.occupants.count()

    def __unicode__(self):
        return '%s - %s (%s)' %  (self.number, self.num_occupants, self.occupants_list())

congregation/forms.py
from django.db import models
from django.forms import ModelForm

from congregation.models import Person

class ProfileForm(ModelForm):
    class META:
        model = Person
        exclude = ('slug', 'user', 'active', 'member', 'role', 'left', 'deceased', 'bslc_individual', )

templates/congregation/base_congregation.html
{% extends "base_site.html" %}

{% block body_class %}congregation{% endblock %}

{% block congregation_search %}
{% if user.is_authenticated %}<form action="{% url congregation_search %}" method="get">
    <div><input type="text" name="findperson" id="findperson" value="church directory search"/><br/><button type="submit">Search</button></div>
{% endif %}
{% endblock%}

templates/congregation/congregation_home.html
{% extends "congregation/base_congregation.html" %}

{% block title %}Group List{% endblock %}
{% block body_class %}{{ block.super }} group_list{% endblock %}


{% block content_title %}
  <h2>Our Congregation</h2>
{% endblock %}

{% block leftnav %}
    <ul>
        <li>Links will go here </li>
    </ul>
{% endblock %}

{% block content %}


</div>
{% endblock %}

templates/congregation/group_list.html
{% extends "congregation/base_congregation.html" %}

{% block title %}Group List{% endblock %}
{% block body_class %}{{ block.super }} group_list{% endblock %}


{% block content %}
<div class="grid_8 sub_page_content">
  <h2>Groups</h2>
  <ul class="link_list">
    {% for group in object_list %}
    <li><a href="{{ group.get_absolute_url }}" title="View posts in this category">{{ group }}</a></li>
    {% endfor %}
  </ul>
</div>
{% endblock %}

templates/congregation/household_detail.html
{% extends "congregation/base_congregation.html" %}
{% load markup %}

{% block title %}{{ object }}{% endblock %}
{% block body_class %}{{ block.super }} household_detail{% endblock %}




{% block content %}
<div class="grid_8 sub_page_content congregation">
  <h2>{{ object }}</h2>
{% if object.picture %}
    <img src="{{ object.picture.image.url }}" height="250px" title="{{ object }}" />
{% endif %}
<h3>Contact Info</h3>
<ul>
    {% if not object.unlisted_number %}<li>Phone: {{ object.household_phone }}</li>{% endif %}
    {% if object.address %}<li>Address: {{ object.full_address }}</li>{% endif %}
</ul>

<h3>Members</h3>
<ul>{% for person in people|dictsort:"directory_report_order" %}
    <li><a href="{{ person.get_absolute_url }}">{{ person }}</a>{% if person.age < 18 and person.age > 0 %} ({{ person.age }}){% endif %}</li>{% endfor %}
</ul>    
<p>For personal contact details, click the individual name</p>
</div>
{% endblock %}

templates/congregation/household_list.html
{% extends "congregation/base_congregation.html" %}

{% block title %} Households List{% endblock %}
{% block body_class %}{{ block.super }} household_list{% endblock %}


{% block content_title %}
  <h2>Households</h2>
{% endblock %}


{% block content %}
        {% if has_previous %}<a href="?page={{  previous }}">&#060;&#060; previous</a> || {% endif %}{% if has_next %}<a href="?page={{ next }}">next &#062;&#062;</a>{% endif %}
        <ul class="link_list"> {% for house in object_list %}
            <li><a href="{{ house.get_absolute_url }}" title="Household detail">{{ house }}</a></li>
            {% endfor %}
        </ul>

{% endblock %}

templates/congregation/mailbox_list.html
{% extends "congregation/base_congregation.html" %}

{% block title %}Malbox List{% endblock %}
{% block body_class %}{{ block.super }} mailbox_list{% endblock %}


{% block content_title %}
  <h2>Church Mailboxes</h2>
{% endblock %}


{% block content %}
  <ul class="link_list">
    {% for box in object_list %}
    <li><a href="{{ box.get_absolute_url }}" title="View posts in this category">{{ box }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}

templates/congregation/person_detail.html
{% extends "congregation/base_congregation.html" %}
{% load markup %}

{% block title %}{{ object }}{% endblock %}
{% block body_class %}{{ block.super }} person_detail{% endblock %}




{% block content %}
<div class="grid_8 sub_page_content">
    <h2>{% if object.prefix %}{{ object.prefix.initials }} {% endif %}{{ object }}</h2>
    {% if this_is_you %}<p>Update <a href="{% url profile_manager %}">your details</a>{% if household_edit %} or <a href="{% url household_manager %}">your household details</a>{% endif %} | <a href="{% url password_change %}">Change your password</a></p>{% endif %}
{% if object.picture %}
    <img class="float_right" src="{{ MEDIA_URL }}{{ object.picture.image }}" height="250px" title="{{ object }}" />
{% endif %}

<h3>Contact Info</h3>
<ul>
    {% if object.landline %}<li> Landline: {{ object.landline }}</li>{% endif %}
    {% if object.cellphone %}<li>Cellphone: {{ object.cellphone }}</li>{% endif %}
    {% if object.email %}<li>Email: <a href="mailto:{{ object.email }}">{{ object.email }}</a></li>{% endif %}
    {% if object.mailbox_set.values %}<li>Church Mailbox # {% for box in  object.mailbox_set.values %}{{box.number}}{% endfor %}</li>{% endif %}
    
</ul>

<h3>About</h3>
<ul>
    <li><a href="{{ object.household.get_absolute_url }}">Household & Address</a></li>
    {% if object.birth_date %}<li>Birthday: {{ object.birth_date|date:"F jS" }}</li>{% endif %}
    {% if object.baptism_date %}<li>Baptized: {{ object.baptism_date|date:"F jS" }}</li>{% endif %}
    {% if object.joined %}<li>Joined: {{ object.joined|date:"F jS, Y" }}</li>{% endif %}

</ul>    
    {% if object.bio %}{{ object.bio|markdown }}{% endif %}
{% if object.role.exists %}
    <h3>Roles</h3>
    <ul>{% for r in object.role.values %}
        <li>{{ r.name }}</li>
    {% endfor %}
    </ul>
{% endif %}

{% if object.leaders.values or object.members.values %}<h3>Groups</h3>
<ul>
    {% if object.leaders.values %}<li>Leader of <ul>{% for group in object.leaders.values %}
    <li>{{ group.name }}</li>{% endfor %}</ul></li>{% endif %}
    {% if object.members.values %}<li>Member of <ul>{% for group in object.members.values %}
    <li>{{ group.name }}</li>{% endfor %}</ul></li>{% endif %}
</ul>
{% endif %}

{% if object.talents.values %}<h3>Talents</h3>
    <ul>{% for talent in object.talents.values %}
        <li>{{ talent }}</li>{% endfor %}
    </ul>
{% endif %}
</div>
{% endblock %}

templates/congregation/person_list.html
{% extends "congregation/base_congregation.html" %}

{% block title %}People{% endblock %}
{% block body_class %}{{ block.super }} people_list{% endblock %}

{% block content %}
        <div class="grid_8 sub_page_content">
            {% block content_title %}
                <h2>{% if search_term %}Results for <strong>{{ search_term }}</strong>{% else %}Congregation Members{% endif %}</h2>
            {% endblock %}
            {% if not message %}
                <ul class="link_list">
                    {% for person in object_list %}
                    <li><a href="{{ person.get_absolute_url }}" title="View individual details">{{ person }}</a>
                        <a href="{{ person.household.get_absolute_url }}"><img src="{{ STATIC_URL }}images/icon_house.gif" 
                        alt="household icon" /></a></li>
                    {% endfor %}
                </ul>
                {% if has_previous %}<a href="?page={{  previous }}">&#060;&#060; previous</a> || {% endif %}{% if has_next %}<a href="?page={{ next }}">next &#062;&#062;</a>{% endif %}
        {% else %}<strong>{{ message }}</strong>{% endif %}
        </div>
{% endblock %}

templates/congregation/profile_manager.html
{% extends "congregation/base_congregation.html" %}
{% load markup %}

{% block congregation_search %}
{% endblock %}


{% block content %}
<div class="grid_8 sub_page_content profile_form">
<h2>Virtual Directory Editor</h2>
<form action="{% url profile_manager %}" method="post">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Save your changes" />
</form>

</div>
{% endblock %}

templates/congregation/search_results.html
{% extends "congregation/base_congregation.html" %}

{% block title %}Search Results{% endblock %}
{% block body_class %}{{ block.super }} people_list{% endblock %}

{% block content %}
<div class="grid_8 sub_page_content">
  <h2>{% if search_term %}Results</h2><h3><strong>{{ message }}'{{ search_term }}'</strong></h3>{% endif %}
  <ul class="link_list">
    {% for person in object_list %}
    <li><a href="{{ person.get_absolute_url }}" title="View individual details">{{ person }}</a> <a href="{{ person.household.get_absolute_url }}"><img src="{{ MEDIA_URL }}images/icon_house.gif" alt="household icon" /></a></li>
    {% endfor %}
  </ul>
</div>
{% endblock %}

templates/congregation/talents_list.html
{% extends "congregation/base_congregation.html" %}

{% block title %}Talents List{% endblock %}
{% block body_class %}{{ block.super }} talents_list{% endblock %}


{% block content_title %}
  <h2>Time and Talents</h2>
{% endblock %}


{% block content %}
  <ul class="link_list">
    {% for talent in object_list %}
    <li><a href="{{ talent.get_absolute_url }}" title="View posts in this category">{{ talent }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}